#!/bin/bash 

alias less='less -r'       # raw control characters
alias vi=vim
alias ci=vi                # Common mistype with disasterous consequences.
alias whence='type -a'     # where, of a sort
alias grep='grep --color'  # show differences in colour
alias l='less -r'
alias R='R -q'
alias date='date "+%F"' 
alias ipython='ipython3'
alias tra='trash'
alias gpp='g++'
alias tp='trash-put'
alias tarp='tar --use-compress-program=pigz'
alias mcrypt='mcrypt -u'
alias rsync='rsync --progress'
alias qs='qstat -a'
alias di='ls'
alias dc='cd ..'
alias qw='watch "qstat -a | grep \ R\ ; qstat -a | grep \ Q\ ; qstat -a | grep \ C\ "'
alias update="sudo apt-get update; sudo apt-get dist-upgrade -y ; sudo apt-get autoremove -y"
alias mod="module"

# Exporting functions makes them available outside the command line.
function py { 
  python3 -u $@ 
}
export -f py
function py2 { 
  python2 -u $@ 
}
export -f py2

# tools shortcuts
alias rr='~/tools/record_run.sh'
alias pssh='~/tools/physics_ssh.sh'
alias pscp='~/tools/physics_scp.sh'
alias psftp='~/tools/physics_sftp.sh'
alias cssh='~/tools/cs_ssh.sh'
alias cscp='~/tools/cs_scp.sh'
alias csftp='~/tools/cs_sftp.sh'
alias ry='~/tools/recycle.sh'

# git shortcuts.
alias gs='git status'
alias gc='git commit'
alias gp='git push'
alias ga='git add'
alias gd='git diff'

# Globus shortcuts.
gflat='c3dc2ae2-74c6-11e8-93bb-0a6d4e044368'
gsdsc='f327a108-b5cd-11e8-8241-0a3b7ca8ce66'

# Lucas's office computer:
hawk='busemey2@hawk.physics.illinois.edu'
# Golub supercomputer
gol='busemey2@golub.campuscluster.illinois.edu'
# Office computer 
#ver='brian@veritas.physics.illinois.edu'
ver='busemey2@128.174.248.144'
# Argonne Mira supercomputer.
mira='busemey@mira.alcf.anl.gov'
# Globus CLI
glob='busemey2@cli.globusonline.org'
# Blue Waters.
bw='busemeye@bw.ncsa.illinois.edu'
