#!/usr/bin/env python3
import sys
import subprocess as sub
import os
import argparse

assert len(sys.argv)==4,"""
  Usage: sub_crystal [num nodes] [time string] [input file]
  """

nnodes=int(sys.argv[1])
nprocs=16*nnodes
time=sys.argv[2]
inpfn=sys.argv[3]

name="%s.%s"%(os.getcwd().split('/')[-1],sys.argv[-1])

outlines = [
    "#!/bin/bash",
    "#PBS -l nodes=%d:ppn=16"%nnodes,
    "#PBS -l walltime=%s"%time,
    "#PBS -j oe",
    "#PBS -m n",
    "#PBS -A bahu",
    "#PBS -q debug",
    "#PBS -N %s"%name,
    "#PBS -o %s.qsub.out"%name,
    "cd %s"%os.getcwd(),
    "cp %s INPUT"%inpfn,
    "aprun -n %d ~/bin/Pcrystal &> %s.out"%(nprocs,name)
  ]
with open("qsub.in",'w') as outf:
  outf.write('\n'.join(outlines))

print(sub.check_output("qsub qsub.in",shell=True))
