#!/usr/bin/env python3
import sys
import subprocess as sub
import os
from argparse import ArgumentParser


dft='(=%(default)s)'
parser=ArgumentParser(sys.argv[0].split('/')[-1])
parser.add_argument('inpfn',type=str,
    help='QWalk input to be submitted.')
parser.add_argument('-np',default=16,type=int,
    help='Number of processors per node.'+dft)
parser.add_argument('-nn',default=1,type=int,
    help='Number of nodes.'+dft)
parser.add_argument('-t',dest='time',default='4:00:00',type=str,
    help='Time string.'+dft)
parser.add_argument('-q',dest='queue',default='secondary',type=str,
    help='Queue.'+dft)
args=parser.parse_args()

assert args.nn==1,"Only set up for 1 node for now, due to OMP usage."

name=args.inpfn

outlines = [
    "#!/bin/bash",
    "#PBS -l nodes=%d:ppn=%d"%(args.nn,args.np),
    "#PBS -l walltime=%s"%args.time,
    "#PBS -N %s"%name,
    "#PBS -e $PBS_JOBID.err",
    "#PBS -o $PBS_JOBID.out",
    "#PBS -q %s"%args.queue,
    "cd %s"%os.getcwd(),
    "export OMP_NUM_THREADS=%d"%(args.nn*args.np),
    "python3 %s &> %s.out"%(args.inpfn,args.inpfn),
  ]

with open('qsub.in','w') as outf:
  outf.write('\n'.join(outlines))

print(sub.check_output("qsub qsub.in",shell=True).decode())
