#!/usr/bin/python
import sys
import subprocess as sub
import os

inpfn = sys.argv[1]
if len(sys.argv) > 2: ppn=int(sys.argv[2])
else:                 ppn = 8
if len(sys.argv) > 3: time = sys.argv[3]
else:                 time = "300:00:00"
cwd = os.getcwd()

outlines = [
    "#PBS -l nodes=1:ppn=%d"%ppn,
    "#PBS -l walltime=%s"%time,
    "#PBS -j oe",
    "#PBS -m n",
    "#PBS -N %s"%inpfn,
    "#PBS -o test.out",
    "cd %s"%cwd
  ]
if ppn > 1:
  outlines += [
      "cp %s INPUT"%inpfn,
      "source add_ompi",
      "source add_intel",
      "nice -n 5 mpirun-1.6.3 -np %d /home/brian/bin/Pcrystal &> %s.out"%(ppn,inpfn),
      "rm *.pe[0-9]"
      "rm *.pe[0-9][0-9]"
    ]
else:
  outlines += ["/home/brian/bin/crystal < {0} >& {0}.out".format(inpfn)]
with open("qsub.in",'w') as outf:
  outf.write('\n'.join(outlines))

print sub.check_output("qsub qsub.in",shell=True)
