#!/usr/bin/python
import sys
import subprocess as sub

inpfn = sys.argv[1]

outlines = [
    "#PBS -l nodes=1:ppn=8",
    "#PBS -l walltime=300:00:00",
    "#PBS -j oe",
    "#PBS -m n",
    "#PBS -N %s"%inpfn,
    "#PBS -o qsub.out",
    "cd ${PBS_O_WORKDIR}",
    "nice -n 5 mpirun -np 8 /home/brian/bin/qwalk {0} >& {0}.out".format(inpfn),
  ]
with open("qsub.in",'w') as outf:
  outf.write('\n'.join(outlines))

print sub.check_output("qsub qsub.in",shell=True)
