#!/usr/bin/env python3
import sys
import subprocess as sub
import os
import mython as my

if len(sys.argv) < 6: np = "allprocs"
else:                 np = int(sys.argv[5])
if len(sys.argv) < 5: nn = 1
else:                 nn = int(sys.argv[4])
if len(sys.argv) < 4: time = "4:00:00"
else:                 time = sys.argv[3]+":00:00"
if len(sys.argv) < 3: queue = "secondary"
else:                 queue = sys.argv[2],
if (len(sys.argv) < 2) or (len(sys.argv) > 6):
  print("Useage: sub_pyscf pyscf_input queue time_in_hours nn np")
  print("Leaving out values generates defaults.")
  raise AssertionError("Bad input")


inpfn = sys.argv[1]
prep=["export PYTHONPATH=/scratch/users/busemey2/molec/pyscf:/home/busemey2/bin:/home/busemey2/programs/qwalk/utils:/home/busemey2/programs/qwalk/utils/autogen:/home/busemey2/tools/busempyer:/home/busemey2/programs/autogenv2:/home/busemey2/programs:/usr/local/python/3.4.0/lib/python3.4/site-packages:/usr/local/python/3.4.0/lib/python34.zip:/usr/local/python/3.4.0/lib/python3.4:/usr/local/python/3.4.0/lib/python3.4/plat-linux:/usr/local/python/3.4.0/lib/python3.4/lib-dynload:/home/busemey2/.local/lib/python3.4/site-packages:../"]
post=[]

qsub = my.gen_qsub_general(
    exelines = ["python3 %s > %s.o"%(inpfn,inpfn)],
    time = time,
    queue = queue,
    name = os.getcwd().split("/")[-1]+'_'+inpfn,
    nn = nn,
    np = np,
    prep_commands=prep,
    final_commands=post
  )

print(sub.check_output("qsub %s"%qsub,shell=True).decode())
