#!/usr/bin/env python3
import sys
import subprocess as sub
import os
import mython as my

assert len(sys.argv)>=3,"""
  Usage: sub_qwalk num_procs inpfiles
  """

nprocs=int(sys.argv[1])
time='100:00:00'
inpfns=' '.join(sys.argv[2:])

name="%s.%s"%(os.getcwd().split('/')[-1],sys.argv[-1])
if len(sys.argv[2:])>1:
  name='bundle'

outlines = [
    "#!/bin/bash",
    "#PBS -l nodes=1:ppn=%d"%nprocs,
    "#PBS -l walltime=%s"%time,
    "#PBS -j oe",
    "#PBS -m n",
    "#PBS -A bahu",
    "#PBS -N %s"%name,
    "#PBS -o %s.qsub.out"%name,
    "cd %s"%os.getcwd(),
    "mpirun -n %d ~/bin/qwalk %s &> %s.out"%(nprocs,inpfns,name),
  ]

with open('qsub.in','w') as outf:
  outf.write('\n'.join(outlines))

print(sub.check_output("qsub qsub.in",shell=True).decode())
