#!/usr/bin/env python3
import sys
import subprocess as sub
import argparse 

dft='(=%(default)s)'
parser=argparse.ArgumentParser("Submit a pyscf run.")
parser.add_argument('inpfn',type=str,
    help='Python script to be submitted.')
parser.add_argument('-np',default=32,type=int,
    help='Number of processors per node.'+dft)
parser.add_argument('-nn',default=1,type=int,
    help='Number of nodes.'+dft)
parser.add_argument('-t',dest='time',default='48:00:00',type=str,
    help='Time string.'+dft)
parser.add_argument('-q',dest='queue',default='normal',type=str,
    help='Queue.'+dft)
args=parser.parse_args()

#assert args.nn==1, "Only tested on one node for now."

prep = [
    "export PYTHONPATH=%s"%(':'.join(sys.path))
  ]
if args.np != "allprocs": 
  prep += [
      "export OMP_NUM_THREADS=%i"%(args.nn*args.np),
    ]
post=[]

qsub_lines=[
    "#!/bin/bash",
    "#PBS -l nodes=%d:ppn=%d:xe"%(args.nn,args.np),
    "#PBS -l walltime=%s"%args.time,
    "#PBS -A bahu",
    "#PBS -N %s"%args.inpfn,
    "#PBS -e $PBS_JOBID.err",
    "#PBS -o $PBS_JOBID.out",
    "#PBS -l gres=shifter",
    "#PBS -q %s"%args.queue,
    "#PBS -v UDI=bbusemeyer/pyscf:latest",
    "",
    "# To add certain modules that you do not have added via ~/.modules",
    ". /opt/modules/default/init/bash",
    "",
    "cd $PBS_O_WORKDIR",
    "export CRAY_ROOTFS=UDI",
    "export PYTHONPATH='/pyscf:/u/sciteam/busemeye/programs/autogenv2'",
    "export OMP_NUM_THREADS=%d"%(args.nn*args.np),
    "aprun -N 1 -n {nn} -d {np} -b -- /usr/local/bin/python  {inp} > {inp}.stdout"\
        .format(nn=args.nn,np=args.np,inp=args.inpfn),
  ]

with open('qsub.in','w') as outf:
  outf.write('\n'.join(qsub_lines))

print(sub.check_output("qsub qsub.in",shell=True).decode())
