#!/usr/bin/perl

$file=$ARGV[0];
if(@ARGV > 1) { $n=$ARGV[1]; } 
else { $n=1; } 
print "
#PBS -l nodes=1:ppn=$n
#PBS -l walltime=300:00:00
#PBS -j oe
#PBS -m n
#PBS -N $ARGV[0]
#PBS -o qsub.out
cd \${PBS_O_WORKDIR}
nice -n 5 python $file $n >& $file.out 
echo `date '+%a %F %T'` `pwd` $file >> ~/completed_jobs
";
