#!/bin/bash 

alias less='less -r'       # raw control characters
alias vi=vim
alias ci=vi                # Common mistype with disasterous consequences.
alias whence='type -a'     # where, of a sort
alias grep='grep --color'  # show differences in colour
alias l='less -r'
alias R='R -q'
alias date='date "+%F"' 
alias ipython='ipython3'
alias tra='trash'
alias gpp='g++'
alias tp='trash-put'
alias tarp='tar --use-compress-program=pigz'
alias mcrypt='mcrypt -u'
alias rsync='rsync --progress'
alias qs='qstat -a'
alias di='ls'
alias dc='cd ..'
alias update="sudo apt-get update; sudo apt-get dist-upgrade -y ; sudo apt-get autoremove -y"
alias mod="module"

# TODO ignore input after these function calls.
function excellent {
  echo "Thank you, sir."
}
function shit {
  echo "Sorry, sir"
}

# Exporting functions makes them available outside the command line.
function py { 
  python3 -W ignore -u $@ 
}
export -f py
function py2 { 
  python2 -W ignore -u $@ 
}
export -f py2

# git shortcuts.
alias gs='git status'
alias gc='git commit'
alias gp='git push'
alias ga='git add'
alias gd='git diff'

# Globus shortcuts.
gflat='c3dc2ae2-74c6-11e8-93bb-0a6d4e044368'
gsdsc='92493232-2535-11eb-b161-0ee0d5d9299f'

# Globus CLI
glob='busemey2@cli.globusonline.org'
